steps:
# build the base image using Kaniko for caching
- name: 'gcr.io/kaniko-project/executor:latest'
  id: DOCKER_BUILD
  args:
  - --destination=gcr.io/$PROJECT_ID/blog
  - --cache=true

# deploy the container to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'blog'
  - '--image'
  - 'gcr.io/$PROJECT_ID/blog'
  - '--platform'
  - 'managed'
  - '--region'
  - 'us-east1'
  - '--allow-unauthenticated'
  id: DEPLOY_CLOUD_RUN
  waitFor: ['DOCKER_BUILD']

timeout: 1200s
